### ISSUE TITLE
Dataset processing

### ISSUE THREAD

**Issue by saqibnaziir** [jchibane/if-net_texture#4]
Hi, thanks for your work. I have downloaded the dataset and set up the environment with all the requirements but when I try to process the dataset using the following command I get the error. I don't know how to fix it. The download dataset I have is in (.npy) format and I guess we have to convert it into (.obj) format but I get the error:
1. 
**$python -m sharp shoot_dir dataset/SHARP2020/challenge1-track1 dataset/SHARP2020/challenge1-track1 --n-shapes 4**
Traceback (most recent call last):
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/__main__.py", line 11, in <module>
    from . import utils
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/utils.py", line 11, in <module>
    from .trirender import UVTrianglesRenderer
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/trirender.py", line 35, in <module>
    class UVTrianglesRenderer:
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/trirender.py", line 112, in UVTrianglesRenderer
    flip_y: bool = True,
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/base_meta_classes.py", line 145, in __getitem__
    args = cls._get_item(item)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/ndarray.py", line 74, in _get_item
    shape, dtype = cls._get_from_tuple(item)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/ndarray.py", line 115, in _get_from_tuple
    shape = cls._get_shape(item[0])
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/ndarray.py", line 129, in _get_shape
    f"Unexpected argument '{dtype_candidate}', expecting"
nptyping.error.InvalidArgumentsError: Unexpected argument '(typing.Any, 2)', expecting Shape[<ShapeExpression>] or Literal[<ShapeExpression>] or typing.Any.

**$python data_processing/convert_to_obj.py**

Finding Paths to convert (from .npz to .obj files).
Start converting.
  0%|                                                                                                                            | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/__main__.py", line 11, in <module>
    from . import utils
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/utils.py", line 11, in <module>
    from .trirender import UVTrianglesRenderer
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/trirender.py", line 35, in <module>
    class UVTrianglesRenderer:
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/trirender.py", line 112, in UVTrianglesRenderer
    flip_y: bool = True,
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/base_meta_classes.py", line 145, in __getitem__
    args = cls._get_item(item)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/ndarray.py", line 74, in _get_item
    shape, dtype = cls._get_from_tuple(item)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/ndarray.py", line 115, in _get_from_tuple
    shape = cls._get_shape(item[0])
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/ndarray.py", line 129, in _get_shape
    f"Unexpected argument '{dtype_candidate}', expecting"
nptyping.error.InvalidArgumentsError: Unexpected argument '(typing.Any, 2)', expecting Shape[<ShapeExpression>] or Literal[<ShapeExpression>] or typing.Any.
Traceback (most recent call last):
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/__main__.py", line 11, in <module>
    from . import utils
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/utils.py", line 11, in <module>
    from .trirender import UVTrianglesRenderer
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/trirender.py", line 35, in <module>
    class UVTrianglesRenderer:
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/sharp/trirender.py", line 112, in UVTrianglesRenderer
    flip_y: bool = True,
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/base_meta_classes.py", line 145, in __getitem__
    args = cls._get_item(item)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/ndarray.py", line 74, in _get_item
    shape, dtype = cls._get_from_tuple(item)
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/ndarray.py", line 115, in _get_from_tuple
    shape = cls._get_shape(item[0])
  File "/home/nazir241/anaconda3/envs/tex_if-net/lib/python3.7/site-packages/nptyping/ndarray.py", line 129, in _get_shape
    f"Unexpected argument '{dtype_candidate}', expecting"
nptyping.error.InvalidArgumentsError: Unexpected argument '(typing.Any, 2)', expecting Shape[<ShapeExpression>] or Literal[<ShapeExpression>] or typing.Any.

**Comment by deepsekk** [comment]
你好，方便提供一些你的下载的数据吗？我无法下载他们官网提供的数据，拜托了
